# Default values for openshift-actions-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: actions-connector

securityContext:
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    capabilities:
      drop:
        - ALL

# REQUIRED VALUE
# oc whoami --show-server
clusterApiServer: ""

################################################################################

serviceAccountName: github-actions
# A rolebinding is created with this role, allowing the application pod to
# modify resources in the namespace
serviceAccountRole: edit

################################################################################

sessionSecretName: connector-session-secrets
sessionSecretKeyName: session-secret
sessionStoreKeyName: session-store-secret

################################################################################

commonLabels:
  app: openshift-actions-connector

deploymentLabels:

################################################################################

serverReplicaCount: 1

serverImage: quay.io/tetchell/openshift-actions-connector
serverTag: latest

serverServiceName: actions-connector
serverHttpPort: 8080
serverHttpPortName: server-http
serverHttpsPort: 8443
serverHttpsPortName: server-https
